version: '3.9'
services:
  bot:
    container_name: oxbot
    build: .
    volumes:
      - ./src:/app/src
    command: ['pnpm', 'dev']

  db:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres/:/var/lib/postgresql/data
  